"Settings by hbzhao"
colorscheme desert    " 颜色主题"
filetype on           " 类型探测打开"
filetype indent on    " 缩进打开"
filetype plugin on    " 自动加载相关插件脚本"
syntax on             " 语法高亮"
set number            " 显示行数"
set cursorcolumn      " 光标列高亮"
set cursorline        " 光标行高亮"
set nocompatible      " 不兼容vi模式"
set nobackup          " 关闭备份文件"
set noswapfile        " 关闭交换文件"
set softtabstop=4     " 设置缩进宽度为4"
set shiftwidth=4      " 设置缩进宽度为4"
set laststatus=2      " 设置显示底行"
set statusline=%m[%F]%y[%{&ff}]%*%=[%l:%c][%p%%]  " 底行内容"
set encoding=utf-8                        " 显示消息时的编码"
set termencoding=utf-8                    " 终端显示用的编码"
set fileencoding=utf-8                    " 打开文件时的编码"
set fileencodings=utf-8,cp936,gbk,ucs-bom " 打开文件尝试编码"
set guifont=Consolas:h12:cANSI:qDRAFT     " 设置字体格式大小"

map <c-j> <c-w>j      " 下移窗口"
map <c-k> <c-w>k      " 上移窗口"
map <c-l> <c-w>l      " 右移窗口"
map <c-h> <c-w>h      " 左移窗口"

inoremap ;; <ESC>     " 快速模式"
nnoremap QQ :qa!<CR>  " 快速退出"
